site_name: Battery Emulator
site_description: Documentation (Wiki) for Battery Emulator
site_url: https://dalathegreat.github.io/Battery-Emulator-Wiki
repo_name: 'dalathegreat/Battery-Emulator'
repo_url: 'https://github.com/dalathegreat/Battery-Emulator'
edit_uri: 'https://github.com/dalathegreat/Battery-Emulator-Wiki/blob/main/docs/'
docs_dir: docs
validation:
  links:
    absolute_links: relative_to_docs
theme:
  name: material
  logo: assets/be.svg
  favicon: assets/be.ico
  language: 'en'
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
#    - navigation.tracking
#    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.action.edit
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      info: octicons/info-16
      warning: octicons/alert-16
      danger: octicons/zap-16
  font:
#    text: Barlow
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/patreon
      link: 'https://www.patreon.com/dala'
    - icon: fontawesome/brands/github
      link: 'https://github.com/dalathegreat/Battery-Emulator'
markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 4
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.details
#  - def_list
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
plugins:
#  - minify:
#      minify_html: true
#  - offline
  - search:
      lang:
        - en
  - awesome-nav
  - redirects:
      redirect_maps:
          'bmsreset.md': 'setup/hardware/periodic_bms_reset.md#taking-it-into-use'
          'battery/aiways_u5_2021.md': 'battery/wip/aiways_u5_2021.md'
          'battery/byd_dolphin_seal_seagull.md': 'battery/wip/byd_dolphin_seal_seagull.md'
          'battery/ccs_bidirectional_charging.md': 'battery/wip/ccs_bidirectional_charging.md'
          'battery/chademo_vehicle.md': 'battery/wip/chademo_vehicle.md'
          'battery/fisker_ocean.md': 'battery/wip/fisker_ocean.md'
          'battery/ford_f_150_lightning.md': 'battery/wip/ford_f_150_lightning.md'
          'battery/geely_gea_platform_galaxy_emas.md': 'battery/wip/geely_gea_platform_galaxy_emas.md'
          'battery/kia_soul.md': 'battery/wip/kia_soul.md'
          'battery/kia_xceed_phev.md': 'battery/wip/kia_xceed_phev.md'
          'battery/land_rover.md': 'battery/wip/land_rover.md'
          'battery/maxus_ed3.md': 'battery/wip/maxus_ed3.md'
          'battery/maxus_ev80.md': 'battery/wip/maxus_ev80.md'
          'battery/mg4.md': 'battery/wip/mg4.md'
          'battery/nissan_ariya.md': 'battery/wip/nissan_ariya.md'
          'battery/omoda.md': 'battery/wip/omoda.md'
          'battery/seres_3.md': 'battery/wip/seres_3.md'
          'battery/smart_eq_fortwo_forfour.md': 'battery/wip/smart_eq_fortwo_forfour.md'
          'battery/stellantis_smp_platform.md': 'battery/wip/stellantis_smp_platform.md'
          'battery/taycan_e_tron.md': 'battery/wip/taycan_e_tron.md'
          'inverter/huawei_sun2000.md': 'inverter/wip/huawei_sun2000.md'
          'inverter/vevor.md': 'inverter/wip/vevor.md'

